{
  "uid" : "50012d5aa6efe433",
  "name" : "test_registration_negative[new email and empty birthday-Auto Test--autotest_N@1728608130.097325.com-password-password-error_message4]",
  "fullName" : "tests.registration_page_test.TestRegistrationPage#test_registration_negative",
  "historyId" : "e62cb237b516e12900469e64b6460cac",
  "time" : {
    "start" : 1728608237677,
    "stop" : 1728608237677,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55db5c6b402a <unknown>\n#1 0x55db5c39a5e0 <unknown>\n#2 0x55db5c3927eb <unknown>\n#3 0x55db5c382a09 <unknown>\n#4 0x55db5c384744 <unknown>\n#5 0x55db5c382cbd <unknown>\n#6 0x55db5c38252f <unknown>\n#7 0x55db5c382422 <unknown>\n#8 0x55db5c380493 <unknown>\n#9 0x55db5c380ada <unknown>\n#10 0x55db5c39cf41 <unknown>\n#11 0x55db5c42e8c5 <unknown>\n#12 0x55db5c40eb22 <unknown>\n#13 0x55db5c42dd7d <unknown>\n#14 0x55db5c40e8c3 <unknown>\n#15 0x55db5c3dc6b3 <unknown>\n#16 0x55db5c3dd68e <unknown>\n#17 0x55db5c67ea2b <unknown>\n#18 0x55db5c6829b1 <unknown>\n#19 0x55db5c66b225 <unknown>\n#20 0x55db5c683532 <unknown>\n#21 0x55db5c65038f <unknown>\n#22 0x55db5c6a2f28 <unknown>\n#23 0x55db5c6a30f3 <unknown>\n#24 0x55db5c6b2e7c <unknown>\n#25 0x7fb183694ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"fd9d1d8f907d9aad61aacbc84c4a388f\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb25e21e6f0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55db5c6a30f3 \\\\u003Cunknown>\\\\n#24 0x55db5c6b2e7c \\\\u003Cunknown>\\\\n#25 0x7fb183694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55db5c6b402a <unknown>\nE       #1 0x55db5c39a5e0 <unknown>\nE       #2 0x55db5c3927eb <unknown>\nE       #3 0x55db5c382a09 <unknown>\nE       #4 0x55db5c384744 <unknown>\nE       #5 0x55db5c382cbd <unknown>\nE       #6 0x55db5c38252f <unknown>\nE       #7 0x55db5c382422 <unknown>\nE       #8 0x55db5c380493 <unknown>\nE       #9 0x55db5c380ada <unknown>\nE       #10 0x55db5c39cf41 <unknown>\nE       #11 0x55db5c42e8c5 <unknown>\nE       #12 0x55db5c40eb22 <unknown>\nE       #13 0x55db5c42dd7d <unknown>\nE       #14 0x55db5c40e8c3 <unknown>\nE       #15 0x55db5c3dc6b3 <unknown>\nE       #16 0x55db5c3dd68e <unknown>\nE       #17 0x55db5c67ea2b <unknown>\nE       #18 0x55db5c6829b1 <unknown>\nE       #19 0x55db5c66b225 <unknown>\nE       #20 0x55db5c683532 <unknown>\nE       #21 0x55db5c65038f <unknown>\nE       #22 0x55db5c6a2f28 <unknown>\nE       #23 0x55db5c6a30f3 <unknown>\nE       #24 0x55db5c6b2e7c <unknown>\nE       #25 0x7fb183694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1728608237678,
      "stop" : 1728608238454,
      "duration" : 776
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728608130626,
      "stop" : 1728608130626,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728608238454,
      "stop" : 1728608238933,
      "duration" : 479
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55db5c6b402a <unknown>\n#1 0x55db5c39a5e0 <unknown>\n#2 0x55db5c3927eb <unknown>\n#3 0x55db5c382a09 <unknown>\n#4 0x55db5c384744 <unknown>\n#5 0x55db5c382cbd <unknown>\n#6 0x55db5c38252f <unknown>\n#7 0x55db5c382422 <unknown>\n#8 0x55db5c380493 <unknown>\n#9 0x55db5c380ada <unknown>\n#10 0x55db5c39cf41 <unknown>\n#11 0x55db5c42e8c5 <unknown>\n#12 0x55db5c40eb22 <unknown>\n#13 0x55db5c42dd7d <unknown>\n#14 0x55db5c40e8c3 <unknown>\n#15 0x55db5c3dc6b3 <unknown>\n#16 0x55db5c3dd68e <unknown>\n#17 0x55db5c67ea2b <unknown>\n#18 0x55db5c6829b1 <unknown>\n#19 0x55db5c66b225 <unknown>\n#20 0x55db5c683532 <unknown>\n#21 0x55db5c65038f <unknown>\n#22 0x55db5c6a2f28 <unknown>\n#23 0x55db5c6a30f3 <unknown>\n#24 0x55db5c6b2e7c <unknown>\n#25 0x7fb183694ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728608238454,
        "stop" : 1728608238933,
        "duration" : 479
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55db5c6b402a <unknown>\n#1 0x55db5c39a5e0 <unknown>\n#2 0x55db5c3927eb <unknown>\n#3 0x55db5c382a09 <unknown>\n#4 0x55db5c384744 <unknown>\n#5 0x55db5c382cbd <unknown>\n#6 0x55db5c38252f <unknown>\n#7 0x55db5c382422 <unknown>\n#8 0x55db5c380493 <unknown>\n#9 0x55db5c380ada <unknown>\n#10 0x55db5c39cf41 <unknown>\n#11 0x55db5c42e8c5 <unknown>\n#12 0x55db5c40eb22 <unknown>\n#13 0x55db5c42dd7d <unknown>\n#14 0x55db5c40e8c3 <unknown>\n#15 0x55db5c3dc6b3 <unknown>\n#16 0x55db5c3dd68e <unknown>\n#17 0x55db5c67ea2b <unknown>\n#18 0x55db5c6829b1 <unknown>\n#19 0x55db5c66b225 <unknown>\n#20 0x55db5c683532 <unknown>\n#21 0x55db5c65038f <unknown>\n#22 0x55db5c6a2f28 <unknown>\n#23 0x55db5c6a30f3 <unknown>\n#24 0x55db5c6b2e7c <unknown>\n#25 0x7fb183694ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"fd9d1d8f907d9aad61aacbc84c4a388f\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728608238968,
      "stop" : 1728608239030,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Registration Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "registration_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestRegistrationPage"
  }, {
    "name" : "host",
    "value" : "fv-az523-260"
  }, {
    "name" : "thread",
    "value" : "2358-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.registration_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "birthday",
    "value" : "''"
  }, {
    "name" : "confirm_password",
    "value" : "'password'"
  }, {
    "name" : "email",
    "value" : "'autotest_N@1728608130.097325.com'"
  }, {
    "name" : "error_message",
    "value" : "['Invalid date', 'Некорректная дата']"
  }, {
    "name" : "first_name",
    "value" : "'Auto Test'"
  }, {
    "name" : "password",
    "value" : "'password'"
  }, {
    "name" : "title",
    "value" : "'new email and empty birthday'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "50012d5aa6efe433.json",
  "parameterValues" : [ "''", "'password'", "'autotest_N@1728608130.097325.com'", "['Invalid date', 'Некорректная дата']", "'Auto Test'", "'password'", "'new email and empty birthday'" ]
}