{
  "uid" : "2728d88003b6234f",
  "name" : "test_registration_negative[an existing email-Auto Test-2023-test_brainup@mail.ru-password-password-The email address is already in use by another account.]",
  "fullName" : "tests.registration_page_test.TestRegistrationPage#test_registration_negative",
  "historyId" : "75ab350f07534d8cd903d5c755491be6",
  "time" : {
    "start" : 1728694625047,
    "stop" : 1728694625047,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55a5cd6cb02a <unknown>\n#1 0x55a5cd3b15e0 <unknown>\n#2 0x55a5cd3a97eb <unknown>\n#3 0x55a5cd399a09 <unknown>\n#4 0x55a5cd39b744 <unknown>\n#5 0x55a5cd399cbd <unknown>\n#6 0x55a5cd39952f <unknown>\n#7 0x55a5cd399422 <unknown>\n#8 0x55a5cd397493 <unknown>\n#9 0x55a5cd397ada <unknown>\n#10 0x55a5cd3b3f41 <unknown>\n#11 0x55a5cd4458c5 <unknown>\n#12 0x55a5cd425b22 <unknown>\n#13 0x55a5cd444d7d <unknown>\n#14 0x55a5cd4258c3 <unknown>\n#15 0x55a5cd3f36b3 <unknown>\n#16 0x55a5cd3f468e <unknown>\n#17 0x55a5cd695a2b <unknown>\n#18 0x55a5cd6999b1 <unknown>\n#19 0x55a5cd682225 <unknown>\n#20 0x55a5cd69a532 <unknown>\n#21 0x55a5cd66738f <unknown>\n#22 0x55a5cd6b9f28 <unknown>\n#23 0x55a5cd6ba0f3 <unknown>\n#24 0x55a5cd6c9e7c <unknown>\n#25 0x7ff6f0494ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"89c9f4e3c5ab52ed1b3ab094fc184e46\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f8f5b3c2d80>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55a5cd6ba0f3 \\\\u003Cunknown>\\\\n#24 0x55a5cd6c9e7c \\\\u003Cunknown>\\\\n#25 0x7ff6f0494ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55a5cd6cb02a <unknown>\nE       #1 0x55a5cd3b15e0 <unknown>\nE       #2 0x55a5cd3a97eb <unknown>\nE       #3 0x55a5cd399a09 <unknown>\nE       #4 0x55a5cd39b744 <unknown>\nE       #5 0x55a5cd399cbd <unknown>\nE       #6 0x55a5cd39952f <unknown>\nE       #7 0x55a5cd399422 <unknown>\nE       #8 0x55a5cd397493 <unknown>\nE       #9 0x55a5cd397ada <unknown>\nE       #10 0x55a5cd3b3f41 <unknown>\nE       #11 0x55a5cd4458c5 <unknown>\nE       #12 0x55a5cd425b22 <unknown>\nE       #13 0x55a5cd444d7d <unknown>\nE       #14 0x55a5cd4258c3 <unknown>\nE       #15 0x55a5cd3f36b3 <unknown>\nE       #16 0x55a5cd3f468e <unknown>\nE       #17 0x55a5cd695a2b <unknown>\nE       #18 0x55a5cd6999b1 <unknown>\nE       #19 0x55a5cd682225 <unknown>\nE       #20 0x55a5cd69a532 <unknown>\nE       #21 0x55a5cd66738f <unknown>\nE       #22 0x55a5cd6b9f28 <unknown>\nE       #23 0x55a5cd6ba0f3 <unknown>\nE       #24 0x55a5cd6c9e7c <unknown>\nE       #25 0x7ff6f0494ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728694482412,
      "stop" : 1728694482412,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728694625048,
      "stop" : 1728694625819,
      "duration" : 771
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728694625819,
      "stop" : 1728694626452,
      "duration" : 633
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55a5cd6cb02a <unknown>\n#1 0x55a5cd3b15e0 <unknown>\n#2 0x55a5cd3a97eb <unknown>\n#3 0x55a5cd399a09 <unknown>\n#4 0x55a5cd39b744 <unknown>\n#5 0x55a5cd399cbd <unknown>\n#6 0x55a5cd39952f <unknown>\n#7 0x55a5cd399422 <unknown>\n#8 0x55a5cd397493 <unknown>\n#9 0x55a5cd397ada <unknown>\n#10 0x55a5cd3b3f41 <unknown>\n#11 0x55a5cd4458c5 <unknown>\n#12 0x55a5cd425b22 <unknown>\n#13 0x55a5cd444d7d <unknown>\n#14 0x55a5cd4258c3 <unknown>\n#15 0x55a5cd3f36b3 <unknown>\n#16 0x55a5cd3f468e <unknown>\n#17 0x55a5cd695a2b <unknown>\n#18 0x55a5cd6999b1 <unknown>\n#19 0x55a5cd682225 <unknown>\n#20 0x55a5cd69a532 <unknown>\n#21 0x55a5cd66738f <unknown>\n#22 0x55a5cd6b9f28 <unknown>\n#23 0x55a5cd6ba0f3 <unknown>\n#24 0x55a5cd6c9e7c <unknown>\n#25 0x7ff6f0494ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728694625819,
        "stop" : 1728694626452,
        "duration" : 633
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55a5cd6cb02a <unknown>\n#1 0x55a5cd3b15e0 <unknown>\n#2 0x55a5cd3a97eb <unknown>\n#3 0x55a5cd399a09 <unknown>\n#4 0x55a5cd39b744 <unknown>\n#5 0x55a5cd399cbd <unknown>\n#6 0x55a5cd39952f <unknown>\n#7 0x55a5cd399422 <unknown>\n#8 0x55a5cd397493 <unknown>\n#9 0x55a5cd397ada <unknown>\n#10 0x55a5cd3b3f41 <unknown>\n#11 0x55a5cd4458c5 <unknown>\n#12 0x55a5cd425b22 <unknown>\n#13 0x55a5cd444d7d <unknown>\n#14 0x55a5cd4258c3 <unknown>\n#15 0x55a5cd3f36b3 <unknown>\n#16 0x55a5cd3f468e <unknown>\n#17 0x55a5cd695a2b <unknown>\n#18 0x55a5cd6999b1 <unknown>\n#19 0x55a5cd682225 <unknown>\n#20 0x55a5cd69a532 <unknown>\n#21 0x55a5cd66738f <unknown>\n#22 0x55a5cd6b9f28 <unknown>\n#23 0x55a5cd6ba0f3 <unknown>\n#24 0x55a5cd6c9e7c <unknown>\n#25 0x7ff6f0494ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"89c9f4e3c5ab52ed1b3ab094fc184e46\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728694626483,
      "stop" : 1728694626545,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Registration Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "registration_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestRegistrationPage"
  }, {
    "name" : "host",
    "value" : "fv-az1245-423"
  }, {
    "name" : "thread",
    "value" : "2340-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.registration_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "birthday",
    "value" : "2023"
  }, {
    "name" : "confirm_password",
    "value" : "'password'"
  }, {
    "name" : "email",
    "value" : "'test_brainup@mail.ru'"
  }, {
    "name" : "error_message",
    "value" : "'The email address is already in use by another account.'"
  }, {
    "name" : "first_name",
    "value" : "'Auto Test'"
  }, {
    "name" : "password",
    "value" : "'password'"
  }, {
    "name" : "title",
    "value" : "'an existing email'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 0,
        "passed" : 5,
        "unknown" : 0,
        "total" : 6
      },
      "items" : [ {
        "uid" : "27ad45015bbc2dac",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/252//#testresult/27ad45015bbc2dac",
        "status" : "passed",
        "time" : {
          "start" : 1725960203968,
          "stop" : 1725960205175,
          "duration" : 1207
        }
      }, {
        "uid" : "3e28b67671df234f",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/239//#testresult/3e28b67671df234f",
        "status" : "passed",
        "time" : {
          "start" : 1725440347425,
          "stop" : 1725440348626,
          "duration" : 1201
        }
      }, {
        "uid" : "fa4ff83d41c3423d",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/66//#testresult/fa4ff83d41c3423d",
        "status" : "passed",
        "time" : {
          "start" : 1721437049659,
          "stop" : 1721437050798,
          "duration" : 1139
        }
      }, {
        "uid" : "25936e24cb3ada32",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/82//#testresult/25936e24cb3ada32",
        "status" : "passed",
        "time" : {
          "start" : 1719309347564,
          "stop" : 1719309348731,
          "duration" : 1167
        }
      }, {
        "uid" : "a82f996b4c5bf9a9",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/20//#testresult/a82f996b4c5bf9a9",
        "status" : "passed",
        "time" : {
          "start" : 1717462393193,
          "stop" : 1717462394334,
          "duration" : 1141
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "2728d88003b6234f.json",
  "parameterValues" : [ "2023", "'password'", "'test_brainup@mail.ru'", "'The email address is already in use by another account.'", "'Auto Test'", "'password'", "'an existing email'" ]
}