{
  "uid" : "495edf2ad12beb4a",
  "name" : "Verify presence, visibility, clickability, href, status code of links in sections",
  "fullName" : "tests.used_resources_page_test.TestUsedResourcesPageLinks#test_ur_03_01_verify_links_in_sections",
  "historyId" : "ebe9470da09a74de61be9fc501f24d7e",
  "time" : {
    "start" : 1728694703463,
    "stop" : 1728694703463,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5612902cf02a <unknown>\n#1 0x56128ffb55e0 <unknown>\n#2 0x56128ffad7eb <unknown>\n#3 0x56128ff9da09 <unknown>\n#4 0x56128ff9f744 <unknown>\n#5 0x56128ff9dcbd <unknown>\n#6 0x56128ff9d52f <unknown>\n#7 0x56128ff9d422 <unknown>\n#8 0x56128ff9b493 <unknown>\n#9 0x56128ff9bada <unknown>\n#10 0x56128ffb7f41 <unknown>\n#11 0x5612900498c5 <unknown>\n#12 0x561290029b22 <unknown>\n#13 0x561290048d7d <unknown>\n#14 0x5612900298c3 <unknown>\n#15 0x56128fff76b3 <unknown>\n#16 0x56128fff868e <unknown>\n#17 0x561290299a2b <unknown>\n#18 0x56129029d9b1 <unknown>\n#19 0x561290286225 <unknown>\n#20 0x56129029e532 <unknown>\n#21 0x56129026b38f <unknown>\n#22 0x5612902bdf28 <unknown>\n#23 0x5612902be0f3 <unknown>\n#24 0x5612902cde7c <unknown>\n#25 0x7f7935e94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"0fe9ef9f3c618030acfb1d51ea7c8ac4\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f8f5b2cbf50>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x5612902be0f3 \\\\u003Cunknown>\\\\n#24 0x5612902cde7c \\\\u003Cunknown>\\\\n#25 0x7f7935e94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x5612902cf02a <unknown>\nE       #1 0x56128ffb55e0 <unknown>\nE       #2 0x56128ffad7eb <unknown>\nE       #3 0x56128ff9da09 <unknown>\nE       #4 0x56128ff9f744 <unknown>\nE       #5 0x56128ff9dcbd <unknown>\nE       #6 0x56128ff9d52f <unknown>\nE       #7 0x56128ff9d422 <unknown>\nE       #8 0x56128ff9b493 <unknown>\nE       #9 0x56128ff9bada <unknown>\nE       #10 0x56128ffb7f41 <unknown>\nE       #11 0x5612900498c5 <unknown>\nE       #12 0x561290029b22 <unknown>\nE       #13 0x561290048d7d <unknown>\nE       #14 0x5612900298c3 <unknown>\nE       #15 0x56128fff76b3 <unknown>\nE       #16 0x56128fff868e <unknown>\nE       #17 0x561290299a2b <unknown>\nE       #18 0x56129029d9b1 <unknown>\nE       #19 0x561290286225 <unknown>\nE       #20 0x56129029e532 <unknown>\nE       #21 0x56129026b38f <unknown>\nE       #22 0x5612902bdf28 <unknown>\nE       #23 0x5612902be0f3 <unknown>\nE       #24 0x5612902cde7c <unknown>\nE       #25 0x7f7935e94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728694482412,
      "stop" : 1728694482412,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728694703463,
      "stop" : 1728694704232,
      "duration" : 769
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728694704233,
      "stop" : 1728694704865,
      "duration" : 632
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5612902cf02a <unknown>\n#1 0x56128ffb55e0 <unknown>\n#2 0x56128ffad7eb <unknown>\n#3 0x56128ff9da09 <unknown>\n#4 0x56128ff9f744 <unknown>\n#5 0x56128ff9dcbd <unknown>\n#6 0x56128ff9d52f <unknown>\n#7 0x56128ff9d422 <unknown>\n#8 0x56128ff9b493 <unknown>\n#9 0x56128ff9bada <unknown>\n#10 0x56128ffb7f41 <unknown>\n#11 0x5612900498c5 <unknown>\n#12 0x561290029b22 <unknown>\n#13 0x561290048d7d <unknown>\n#14 0x5612900298c3 <unknown>\n#15 0x56128fff76b3 <unknown>\n#16 0x56128fff868e <unknown>\n#17 0x561290299a2b <unknown>\n#18 0x56129029d9b1 <unknown>\n#19 0x561290286225 <unknown>\n#20 0x56129029e532 <unknown>\n#21 0x56129026b38f <unknown>\n#22 0x5612902bdf28 <unknown>\n#23 0x5612902be0f3 <unknown>\n#24 0x5612902cde7c <unknown>\n#25 0x7f7935e94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728694704233,
        "stop" : 1728694704865,
        "duration" : 632
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5612902cf02a <unknown>\n#1 0x56128ffb55e0 <unknown>\n#2 0x56128ffad7eb <unknown>\n#3 0x56128ff9da09 <unknown>\n#4 0x56128ff9f744 <unknown>\n#5 0x56128ff9dcbd <unknown>\n#6 0x56128ff9d52f <unknown>\n#7 0x56128ff9d422 <unknown>\n#8 0x56128ff9b493 <unknown>\n#9 0x56128ff9bada <unknown>\n#10 0x56128ffb7f41 <unknown>\n#11 0x5612900498c5 <unknown>\n#12 0x561290029b22 <unknown>\n#13 0x561290048d7d <unknown>\n#14 0x5612900298c3 <unknown>\n#15 0x56128fff76b3 <unknown>\n#16 0x56128fff868e <unknown>\n#17 0x561290299a2b <unknown>\n#18 0x56129029d9b1 <unknown>\n#19 0x561290286225 <unknown>\n#20 0x56129029e532 <unknown>\n#21 0x56129026b38f <unknown>\n#22 0x5612902bdf28 <unknown>\n#23 0x5612902be0f3 <unknown>\n#24 0x5612902cde7c <unknown>\n#25 0x7f7935e94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"0fe9ef9f3c618030acfb1d51ea7c8ac4\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728694704898,
      "stop" : 1728694704960,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Used Resources Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "used_resources_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestUsedResourcesPage"
  }, {
    "name" : "host",
    "value" : "fv-az1245-423"
  }, {
    "name" : "thread",
    "value" : "2340-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.used_resources_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 1,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 12,
        "unknown" : 0,
        "total" : 17
      },
      "items" : [ {
        "uid" : "e37e0fe8de05fb92",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/149//#testresult/e37e0fe8de05fb92",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55ce4c03802a <unknown>\n#1 0x55ce4bd1e5e0 <unknown>\n#2 0x55ce4bd167eb <unknown>\n#3 0x55ce4bd06a09 <unknown>\n#4 0x55ce4bd08744 <unknown>\n#5 0x55ce4bd06cbd <unknown>\n#6 0x55ce4bd0652f <unknown>\n#7 0x55ce4bd06422 <unknown>\n#8 0x55ce4bd04493 <unknown>\n#9 0x55ce4bd04ada <unknown>\n#10 0x55ce4bd20f41 <unknown>\n#11 0x55ce4bdb28c5 <unknown>\n#12 0x55ce4bd92b22 <unknown>\n#13 0x55ce4bdb1d7d <unknown>\n#14 0x55ce4bd928c3 <unknown>\n#15 0x55ce4bd606b3 <unknown>\n#16 0x55ce4bd6168e <unknown>\n#17 0x55ce4c002a2b <unknown>\n#18 0x55ce4c0069b1 <unknown>\n#19 0x55ce4bfef225 <unknown>\n#20 0x55ce4c007532 <unknown>\n#21 0x55ce4bfd438f <unknown>\n#22 0x55ce4c026f28 <unknown>\n#23 0x55ce4c0270f3 <unknown>\n#24 0x55ce4c036e7c <unknown>\n#25 0x7f0e2ce94ac3 <unknown>",
        "time" : {
          "start" : 1728608302346,
          "stop" : 1728608302346,
          "duration" : 0
        }
      }, {
        "uid" : "3d7aab46a33c09ab",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/322//#testresult/3d7aab46a33c09ab",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20090601012031/http://caliban.mpiz-koeln.mpg.de/~stueber/thome/Alphabetical_list.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f222a646cf0>, 'Connection to web.archive.org timed out. (connect timeout=None)'))",
        "time" : {
          "start" : 1728557923827,
          "stop" : 1728558059915,
          "duration" : 136088
        }
      }, {
        "uid" : "eb1db24f8fd7410e",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/321//#testresult/eb1db24f8fd7410e",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20090601012031/http://caliban.mpiz-koeln.mpg.de/~stueber/thome/Alphabetical_list.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efe98e60e60>, 'Connection to web.archive.org timed out. (connect timeout=None)'))",
        "time" : {
          "start" : 1728554822455,
          "stop" : 1728554957575,
          "duration" : 135120
        }
      }, {
        "uid" : "dab4049b5b7aeb43",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/148//#testresult/dab4049b5b7aeb43",
        "status" : "passed",
        "time" : {
          "start" : 1728522882744,
          "stop" : 1728522884055,
          "duration" : 1311
        }
      }, {
        "uid" : "65d585b278c513ea",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/320//#testresult/65d585b278c513ea",
        "status" : "passed",
        "time" : {
          "start" : 1728471156677,
          "stop" : 1728471160974,
          "duration" : 4297
        }
      }, {
        "uid" : "4848cf7586c81cae",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/319//#testresult/4848cf7586c81cae",
        "status" : "passed",
        "time" : {
          "start" : 1728468625135,
          "stop" : 1728468626619,
          "duration" : 1484
        }
      }, {
        "uid" : "25ee8b67871849fd",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/147//#testresult/25ee8b67871849fd",
        "status" : "passed",
        "time" : {
          "start" : 1728436607740,
          "stop" : 1728436609285,
          "duration" : 1545
        }
      }, {
        "uid" : "d7e053ef083ca417",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/318//#testresult/d7e053ef083ca417",
        "status" : "passed",
        "time" : {
          "start" : 1728378575515,
          "stop" : 1728378577470,
          "duration" : 1955
        }
      }, {
        "uid" : "82afea025452a9db",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/317//#testresult/82afea025452a9db",
        "status" : "passed",
        "time" : {
          "start" : 1728375885381,
          "stop" : 1728375900387,
          "duration" : 15006
        }
      }, {
        "uid" : "1f3bffeaf5d81ab5",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/316//#testresult/1f3bffeaf5d81ab5",
        "status" : "passed",
        "time" : {
          "start" : 1728375529046,
          "stop" : 1728375530652,
          "duration" : 1606
        }
      }, {
        "uid" : "b7237b1d582a99fd",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/146//#testresult/b7237b1d582a99fd",
        "status" : "passed",
        "time" : {
          "start" : 1728349600804,
          "stop" : 1728349602253,
          "duration" : 1449
        }
      }, {
        "uid" : "56a2d3b1547bc7d0",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/315//#testresult/56a2d3b1547bc7d0",
        "status" : "passed",
        "time" : {
          "start" : 1728293685353,
          "stop" : 1728293688779,
          "duration" : 3426
        }
      }, {
        "uid" : "fff63fd701815b4",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/314//#testresult/fff63fd701815b4",
        "status" : "passed",
        "time" : {
          "start" : 1728290740273,
          "stop" : 1728290754456,
          "duration" : 14183
        }
      }, {
        "uid" : "c120c26abe3005e6",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/145//#testresult/c120c26abe3005e6",
        "status" : "passed",
        "time" : {
          "start" : 1728264382230,
          "stop" : 1728264395792,
          "duration" : 13562
        }
      }, {
        "uid" : "be966a822f24ca8b",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/313//#testresult/be966a822f24ca8b",
        "status" : "failed",
        "statusDetails" : "AssertionError: Status codes of links mismatch valid values\nassert False\n +  where False = all(<generator object TestUsedResourcesPage.TestUsedResourcesPageLinks.test_ur_03_01_verify_links_in_sections.<locals>.<genexpr> at 0x7f2fe9214380>)",
        "time" : {
          "start" : 1728227596194,
          "stop" : 1728227601951,
          "duration" : 5757
        }
      }, {
        "uid" : "f48f230b5e6f683b",
        "reportUrl" : "https://Brain-up.github.io/auto-tests-python/312//#testresult/f48f230b5e6f683b",
        "status" : "passed",
        "time" : {
          "start" : 1728222660908,
          "stop" : 1728222662194,
          "duration" : 1286
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "495edf2ad12beb4a.json",
  "parameterValues" : [ ]
}